### PR TITLE
Created a common dialog for jump to position and display the list of the saved mouse positions.

### PR DESCRIPTION
**Pull request by abdel792**
Created a common dialog for jump to position and display the list of the saved mouse positions.

Prevent Multiple Instances When Opening the Dialogs.
Used the gui.guiHelper module to ensure the good appearance of the dialog box listing the saved positions.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,
Please base pull requests from master branch, not stable. Also, there's no need to bump versions or add readme entries. I already took care of Unicode issue. Thanks.

**Comment by josephsl** [comment]
Hi,

You might want to give credit to where it is due, specifically where you got the common dialog code (I know where it came from).

**Comment by abdel792** [comment]
The gui.guiHelper implementation for the list of saved locations comes from the NVDACore, gui /settingsDialog.

It comes from the class DictionaryDialog for an implementation that conformed to the rules used.

If you want, you can add a comment about it.

**Comment by josephsl** [comment]
Hi, that’ll be done. Thanks for the work – directly merged. Thanks.

**Pull request closed without merging**
