### PR TITLE
Replace win32api with winUser module

### PR DESCRIPTION
**Pull request by Robert-J-H**

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Reference: #1.

**Comment by josephsl** [comment]
Thanks. Approved and merged.

**Comment by Robert-J-H** [comment]
Gosh are you fast... ;)
Thanks for merging
Cheers
Robert

**Comment by josephsl** [comment]
Hi, my usual turnaround time is 24 hours, but typically for trivial pull requests like this, it takes about ten minutes to review and merge it. Thanks.

**Pull request merged**
